enum IFacilityFields {
  FACILITIES_ID = 'facilities_id',
  EVENT_ID = 'event_id',
  FACILITIES_DESCRIPTION = 'facilities_description',
  FACILITIES_ABBR = 'facilities_abbr',
  NUM_FIELDS = 'num_fields',
  FACILITIES_TAG = 'facilities_tag',
  ADDRESS1 = 'address1',
  ADDRESS2 = 'address2',
  CITY = 'city',
  STATE = 'state',
  ZIP = 'zip',
  COUNTRY = 'country',
  FACILITY_LAT = 'facility_lat',
  FACILITY_LONG = 'facility_long',
  FACILITY_SORT = 'facility_sort',
  FIRST_GAME_TIME = 'first_game_time',
  LAST_GAME_END = 'last_game_end',
  PUBLIC_ACCESS_YN = 'public_access_YN',
  RESTROOMS = 'restrooms',
  NUM_TOILETS = 'num_toilets',
  RESTROOM_DETAILS = 'restroom_details',
  PARKING_AVAILABLE = 'parking_available',
  PARKING_DETAILS = 'parking_details',
  PARKING_PROXIMITY = 'parking_proximity',
  GOLF_CARTS_AVAILABLE = 'golf_carts_available',
  FIELD_MAP_URL = 'field_map_URL',
  IS_ACTIVE_YN = 'is_active_YN',
  IS_LIBRARY_YN = 'is_library_YN',
  CREATED_BY = 'created_by',
  CREATED_DATETIME = 'created_datetime',
  UPDATED_BY = 'updated_by',
  UPDATED_DATETIME = 'updated_datetime',
}

export { IFacilityFields };
