enum ITeamFields {
  TEAM_ID = 'team_id',
  EVENT_ID = 'event_id',
  ORG_ID = 'org_id',
  LONG_NAME = 'long_name',
  SHORT_NAME = 'short_name',
  TEAM_TAG = 'team_tag',
  CITY = 'city',
  STATE = 'state',
  LEVEL = 'level',
  CONTACT_FIRST_NAME = 'contact_first_name',
  CONTACT_LAST_NAME = 'contact_last_name',
  PHONE_NUM = 'phone_num',
  CONTACT_EMAIL = 'contact_email',
  SCHEDULE_RESTRICTIONS = 'schedule_restrictions',
  IS_ACTIVE_YN = 'is_active_YN',
  IS_LIBRARY_YN = 'is_library_YN',
  CREATED_BY = 'created_by',
  CREATED_DATETIME = 'created_datetime',
  UPDATED_BY = 'updated_by',
  UPDATED_DATETIME = 'updated_datetime',
  DIVISION_ID = 'division_id',
  POOL_ID = 'pool_id',
}

export { ITeamFields };
