enum IDivisionFields {
  DIVISION_ID = 'division_id',
  EVENT_ID = 'event_id',
  LONG_NAME = 'long_name',
  SHORT_NAME = 'short_name',
  IS_PREMIER_YN = 'is_premier_YN',
  ENTRY_FEE = 'entry_fee',
  DIVISION_DESCRIPTION = 'division_description',
  DIVISION_HEX = 'division_hex',
  DIVISION_TAG = 'division_tag',
  MAX_NUM_TEAMS = 'max_num_teams',
  TEAMS_REGISTERED = 'teams_registered',
  TEAMS_TENTITIVE = 'teams_tentitive',
  NUM_POOLS = 'num_pools',
  DIVISION_MESSAGE = 'division_message',
  GAME_DURATION_DIFFER = 'game_duration_differ',
  GAME_DURATION_OVERRIDE = 'game_duration_override',
  UNIQUE_BRACKET_GAME_DURATION = 'unique_bracket_game_duration',
  DIVISION_SORT = 'division_sort',
  LATEST_WEB_PUBLISH = 'latest_web_publish',
  IS_ACTIVE_YN = 'is_active_YN',
  IS_LIBRARY_YN = 'is_library_YN',
  CREATED_BY = 'created_by',
  CREATED_DATETIME = 'created_datetime',
  UPDATED_BY = 'updated_by',
  UPDATED_DATETIME = 'updated_datetime',
}

export { IDivisionFields };
