export const EVENTS_FETCH_SUCCESS = 'EVENTS_FETCH_SUCCESS';
export const EVENTS_FETCH_FAILURE = 'EVENTS_FETCH_FAILURE';
export const DASHBOARD_TEAMS_FETCH_SUCCESS = 'DASHBOARD_TEAMS_FETCH_SUCCESS';
export const FIELDS_FETCH_SUCCESS = 'FIELDS_FETCH_SUCCESS';
export const DASHBOARD_FETCH_START = 'DASHBOARD_FETCH_START';
export const CALENDAR_EVENTS_FETCH_START =
  'DASHBOARD_CALENDAR_EVENTS_FETCH_START';
export const CALENDAR_EVENTS_FETCH_SUCCESS =
  'DASHBOARD_CALENDAR_EVENTS_FETCH_SUCCESS';
export const DASHBOARD_SCHEDULES_FETCH_SUCCESS =
  'DASHBOARD_SCHEDULES_FETCH_SUCCESS';
